/**
 * Hand-written sample data for the mockups in this directory, per
 * PRODUCT.md §11.4. Not fetched (a file:// page cannot fetch JSON), so this
 * assigns a global instead of a sibling .json file.
 *
 * Shape:
 *   SAMPLE_EVENTS.tasks     task_id -> title, a mockup-only convenience map.
 *                           Not part of the §8.3 schema; the real board
 *                           gets titles from backlog/tasks/*.md.
 *   SAMPLE_EVENTS.sessions  rows matching the §8.3 "sessions" table exactly.
 *   SAMPLE_EVENTS.events    every event across every session, each a §5.1
 *                           envelope. Session "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11" (task-101) carries the
 *                           full required narrative: three turns, a tool
 *                           call, a denied permission request, a health
 *                           change to waiting_for_input at tier 0, a nudge,
 *                           and a full takeover/release cycle. The other six
 *                           sessions are deliberately short — each exists
 *                           only to put one more PRODUCT.md §6.1 health
 *                           state on the board.
 *
 * Regenerated by (not committed): scratchpad/gen-sample.js
 */
'use strict';

globalThis.SAMPLE_EVENTS = {
  "tasks": {
    "task-108": "Write end-to-end tests for the CSV importer",
    "task-109": "Draft the changelog for 0.6.0",
    "task-101": "Add retry backoff to the webhook sender",
    "task-102": "Refactor pagination in the tasks list",
    "task-103": "Investigate flaky auth test",
    "task-104": "Bump dependency versions",
    "task-105": "Normalize timezone handling in the scheduler",
    "task-106": "Migrate config loader to async",
    "task-107": "Patch webhook signature verification"
  },
  "sessions": [
    {
      "id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "adapter": "claude",
      "runtime": "local",
      "cwd": "/home/user/webhook-service",
      "started_at": "2026-09-20T14:38:45.189Z",
      "ended_at": "2026-09-20T14:56:24.789Z",
      "health": "done",
      "takeover": "auto",
      "started_by": {
        "reason": "operator_action",
        "actor": "human",
        "caused_by": null
      },
      "ended_by": {
        "reason": "completed",
        "actor": "agent",
        "caused_by": "evt_00043"
      },
      "last_seq": 44,
      "archived": 0
    },
    {
      "id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "adapter": "claude",
      "runtime": "local",
      "cwd": "/home/user/task-board-ui",
      "started_at": "2026-09-20T13:38:45.189Z",
      "ended_at": null,
      "health": "working",
      "takeover": "auto",
      "started_by": {
        "reason": "operator_action",
        "actor": "human",
        "caused_by": null
      },
      "ended_by": null,
      "last_seq": 7,
      "archived": 0
    },
    {
      "id": "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
      "task_id": "task-103",
      "adapter": "claude",
      "runtime": "local",
      "cwd": "/home/user/auth-service",
      "started_at": "2026-09-20T12:38:45.189Z",
      "ended_at": null,
      "health": "waiting_for_input",
      "takeover": "auto",
      "started_by": {
        "reason": "operator_action",
        "actor": "human",
        "caused_by": null
      },
      "ended_by": null,
      "last_seq": 6,
      "archived": 0
    },
    {
      "id": "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
      "task_id": "task-104",
      "adapter": "claude",
      "runtime": "local",
      "cwd": "/home/user/webhook-service",
      "started_at": "2026-09-20T11:38:45.189Z",
      "ended_at": null,
      "health": "rate_limited",
      "takeover": "auto",
      "started_by": {
        "reason": "operator_action",
        "actor": "human",
        "caused_by": null
      },
      "ended_by": null,
      "last_seq": 6,
      "archived": 0
    },
    {
      "id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "adapter": "claude",
      "runtime": "local",
      "cwd": "/home/user/scheduler",
      "started_at": "2026-09-20T10:38:45.189Z",
      "ended_at": null,
      "health": "stuck",
      "takeover": "auto",
      "started_by": {
        "reason": "operator_action",
        "actor": "human",
        "caused_by": null
      },
      "ended_by": null,
      "last_seq": 12,
      "archived": 0
    },
    {
      "id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "adapter": "claude",
      "runtime": "local",
      "cwd": "/home/user/config-loader",
      "started_at": "2026-09-20T09:38:45.189Z",
      "ended_at": "2026-09-20T09:49:25.389Z",
      "health": "crashed",
      "takeover": "auto",
      "started_by": {
        "reason": "operator_action",
        "actor": "human",
        "caused_by": null
      },
      "ended_by": {
        "reason": "crashed",
        "actor": "supervisor",
        "caused_by": "evt_00081"
      },
      "last_seq": 7,
      "archived": 0
    },
    {
      "id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "adapter": "claude",
      "runtime": "local",
      "cwd": "/home/user/webhook-service",
      "started_at": "2026-09-20T13:08:45.189Z",
      "ended_at": null,
      "health": "working",
      "takeover": "human_owned",
      "started_by": {
        "reason": "operator_action",
        "actor": "human",
        "caused_by": null
      },
      "ended_by": null,
      "last_seq": 7,
      "archived": 0
    }
  ],
  "events": [
    {
      "id": "evt_00001",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 1,
      "ts": "2026-09-20T14:38:45.189Z",
      "type": "session.started",
      "actor": "supervisor",
      "caused_by": null,
      "payload": {
        "adapter": "claude",
        "runtime": "local",
        "cwd": "/home/user/webhook-service",
        "argv": [
          "-p",
          "--session-id",
          "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
          "--input-format",
          "stream-json",
          "--output-format",
          "stream-json",
          "--permission-mode",
          "default"
        ],
        "capabilities": [
          "interrupt_receipt_v1",
          "interrupt_cancel_queued_v1"
        ]
      }
    },
    {
      "id": "evt_00002",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 2,
      "ts": "2026-09-20T14:38:45.589Z",
      "type": "process.spawned",
      "actor": "supervisor",
      "caused_by": "evt_00001",
      "payload": {
        "pid": 48213,
        "nonce": "n-7f2a91",
        "argv": [
          "claude",
          "-p",
          "--session-id",
          "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11"
        ],
        "cwd": "/home/user/webhook-service"
      }
    },
    {
      "id": "evt_00003",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 3,
      "ts": "2026-09-20T14:38:45.789Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00002",
      "payload": {
        "turn_index": 1
      }
    },
    {
      "id": "evt_00004",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 4,
      "ts": "2026-09-20T14:38:45.989Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00003",
      "payload": {
        "text": "Add exponential backoff with jitter to the webhook sender's retry loop. Cap at 5 attempts.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00005",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 5,
      "ts": "2026-09-20T14:38:49.389Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00004",
      "payload": {
        "text": "I'll look at the current retry loop first."
      }
    },
    {
      "id": "evt_00006",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 6,
      "ts": "2026-09-20T14:38:49.489Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00005",
      "payload": {
        "tool_name": "Read",
        "tool_input": {
          "file_path": "src/webhook/sender.js"
        },
        "tool_use_id": "tu_001"
      }
    },
    {
      "id": "evt_00007",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 7,
      "ts": "2026-09-20T14:38:50.089Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00006",
      "payload": {
        "tool_use_id": "tu_001",
        "result_ref": null,
        "duration_ms": 120
      }
    },
    {
      "id": "evt_00008",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 8,
      "ts": "2026-09-20T14:38:54.189Z",
      "type": "turn.ended",
      "actor": "supervisor",
      "caused_by": "evt_00007",
      "payload": {
        "turn_index": 1,
        "cost_usd": 0.014,
        "tokens": {
          "input": 1820,
          "output": 96
        }
      }
    },
    {
      "id": "evt_00009",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 9,
      "ts": "2026-09-20T14:38:54.389Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00008",
      "payload": {
        "turn_index": 2
      }
    },
    {
      "id": "evt_00010",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 10,
      "ts": "2026-09-20T14:38:54.589Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00009",
      "payload": {
        "text": "Before I edit, I want to clear the local test cache to rule out stale state."
      }
    },
    {
      "id": "evt_00011",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 11,
      "ts": "2026-09-20T14:38:54.689Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00010",
      "payload": {
        "tool_name": "Bash",
        "tool_input": {
          "command": "rm -rf node_modules/.cache"
        },
        "tool_use_id": "tu_002"
      }
    },
    {
      "id": "evt_00012",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 12,
      "ts": "2026-09-20T14:38:54.789Z",
      "type": "permission.requested",
      "actor": "supervisor",
      "caused_by": "evt_00011",
      "payload": {
        "tool_name": "Bash",
        "tool_input": {
          "command": "rm -rf node_modules/.cache"
        }
      }
    },
    {
      "id": "evt_00013",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 13,
      "ts": "2026-09-20T14:39:11.289Z",
      "type": "permission.decided",
      "actor": "human",
      "caused_by": "evt_00012",
      "payload": {
        "decision": "deny",
        "reason": "Destructive and unrelated to the task; skip it.",
        "decided_by": "operator"
      }
    },
    {
      "id": "evt_00014",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 14,
      "ts": "2026-09-20T14:39:11.489Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00013",
      "payload": {
        "text": "Understood, skipping that. I'll proceed straight to the retry loop."
      }
    },
    {
      "id": "evt_00015",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 15,
      "ts": "2026-09-20T14:39:15.189Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00014",
      "payload": {
        "tool_name": "Edit",
        "tool_input": {
          "file_path": "src/webhook/sender.js",
          "summary": "add exponential backoff with jitter"
        },
        "tool_use_id": "tu_003"
      }
    },
    {
      "id": "evt_00016",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 16,
      "ts": "2026-09-20T14:39:16.689Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00015",
      "payload": {
        "tool_use_id": "tu_003",
        "result_ref": null,
        "duration_ms": 1500
      }
    },
    {
      "id": "evt_00017",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 17,
      "ts": "2026-09-20T14:39:18.189Z",
      "type": "turn.ended",
      "actor": "supervisor",
      "caused_by": "evt_00016",
      "payload": {
        "turn_index": 2,
        "cost_usd": 0.021,
        "tokens": {
          "input": 2510,
          "output": 340
        }
      }
    },
    {
      "id": "evt_00018",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 18,
      "ts": "2026-09-20T14:39:18.389Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00017",
      "payload": {
        "turn_index": 3
      }
    },
    {
      "id": "evt_00019",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 19,
      "ts": "2026-09-20T14:39:18.589Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00018",
      "payload": {
        "text": "Should the backoff cap apply per-endpoint or across the whole sender queue? The ticket doesn't say."
      }
    },
    {
      "id": "evt_00020",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 20,
      "ts": "2026-09-20T14:39:18.789Z",
      "type": "health.changed",
      "actor": "supervisor",
      "caused_by": "evt_00019",
      "payload": {
        "from": "working",
        "to": "waiting_for_input",
        "tier": 0,
        "evidence": {
          "hook": "agent_needs_input"
        }
      }
    },
    {
      "id": "evt_00021",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 21,
      "ts": "2026-09-20T14:54:05.189Z",
      "type": "nudge.sent",
      "actor": "watchdog",
      "caused_by": "evt_00020",
      "payload": {
        "text": "Apply the cap per-endpoint; that matches how the existing rate limiter is scoped.",
        "tier": 2,
        "verdict": "answer_question"
      }
    },
    {
      "id": "evt_00022",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 22,
      "ts": "2026-09-20T14:54:05.389Z",
      "type": "health.changed",
      "actor": "supervisor",
      "caused_by": "evt_00021",
      "payload": {
        "from": "waiting_for_input",
        "to": "working",
        "tier": 2,
        "evidence": {
          "nudge_id": "evt_00021"
        }
      }
    },
    {
      "id": "evt_00023",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 23,
      "ts": "2026-09-20T14:54:09.189Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00022",
      "payload": {
        "text": "Got it — scoping the cap per-endpoint."
      }
    },
    {
      "id": "evt_00024",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 24,
      "ts": "2026-09-20T14:54:13.189Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00023",
      "payload": {
        "tool_name": "Edit",
        "tool_input": {
          "file_path": "src/webhook/sender.js",
          "summary": "scope backoff cap per endpoint"
        },
        "tool_use_id": "tu_004"
      }
    },
    {
      "id": "evt_00025",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 25,
      "ts": "2026-09-20T14:54:14.789Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00024",
      "payload": {
        "tool_use_id": "tu_004",
        "result_ref": null,
        "duration_ms": 1600
      }
    },
    {
      "id": "evt_00026",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 26,
      "ts": "2026-09-20T14:54:18.189Z",
      "type": "turn.ended",
      "actor": "supervisor",
      "caused_by": "evt_00025",
      "payload": {
        "turn_index": 3,
        "cost_usd": 0.018,
        "tokens": {
          "input": 2100,
          "output": 210
        }
      }
    },
    {
      "id": "evt_00027",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 27,
      "ts": "2026-09-20T14:55:15.189Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00026",
      "payload": {
        "turn_index": 4
      }
    },
    {
      "id": "evt_00028",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 28,
      "ts": "2026-09-20T14:55:15.389Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00027",
      "payload": {
        "text": "I'm about to update the config default for maxRetries — should it stay 5, or match the new cap exactly?"
      }
    },
    {
      "id": "evt_00029",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 29,
      "ts": "2026-09-20T14:55:15.589Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00028",
      "payload": {
        "tool_name": "Edit",
        "tool_input": {
          "file_path": "config/webhook.json",
          "summary": "update maxRetries default"
        },
        "tool_use_id": "tu_005"
      }
    },
    {
      "id": "evt_00030",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 30,
      "ts": "2026-09-20T14:55:20.189Z",
      "type": "takeover.requested",
      "actor": "human",
      "caused_by": "evt_00028",
      "payload": {}
    },
    {
      "id": "evt_00031",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 31,
      "ts": "2026-09-20T14:55:21.189Z",
      "type": "takeover.acquired",
      "actor": "human",
      "caused_by": "evt_00030",
      "payload": {}
    },
    {
      "id": "evt_00032",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 32,
      "ts": "2026-09-20T14:55:21.389Z",
      "type": "permission.decided",
      "actor": "supervisor",
      "caused_by": "evt_00031",
      "payload": {
        "decision": "deny",
        "reason": "session is human_owned; agent tool calls are denied while a human holds it",
        "decided_by": "supervisor",
        "tool_use_id": "tu_005"
      }
    },
    {
      "id": "evt_00033",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 33,
      "ts": "2026-09-20T14:55:45.189Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00031",
      "payload": {
        "text": "I'll set it myself — keeping maxRetries at 5, independent of the per-endpoint cap.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00034",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 34,
      "ts": "2026-09-20T14:56:05.189Z",
      "type": "tool.requested",
      "actor": "human",
      "caused_by": "evt_00033",
      "payload": {
        "tool_name": "Edit",
        "tool_input": {
          "file_path": "config/webhook.json",
          "summary": "maxRetries stays 5"
        },
        "tool_use_id": "tu_006"
      }
    },
    {
      "id": "evt_00035",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 35,
      "ts": "2026-09-20T14:56:06.389Z",
      "type": "tool.completed",
      "actor": "human",
      "caused_by": "evt_00034",
      "payload": {
        "tool_use_id": "tu_006",
        "result_ref": null,
        "duration_ms": 1200
      }
    },
    {
      "id": "evt_00036",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 36,
      "ts": "2026-09-20T14:56:15.189Z",
      "type": "takeover.released",
      "actor": "human",
      "caused_by": "evt_00035",
      "payload": {}
    },
    {
      "id": "evt_00037",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 37,
      "ts": "2026-09-20T14:56:16.189Z",
      "type": "turn.ended",
      "actor": "supervisor",
      "caused_by": "evt_00036",
      "payload": {
        "turn_index": 4,
        "cost_usd": 0.006,
        "tokens": {
          "input": 640,
          "output": 40
        }
      }
    },
    {
      "id": "evt_00038",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 38,
      "ts": "2026-09-20T14:56:16.389Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00037",
      "payload": {
        "turn_index": 5
      }
    },
    {
      "id": "evt_00039",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 39,
      "ts": "2026-09-20T14:56:16.589Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00038",
      "payload": {
        "text": "Config looks right. Running the test suite to confirm."
      }
    },
    {
      "id": "evt_00040",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 40,
      "ts": "2026-09-20T14:56:16.789Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00039",
      "payload": {
        "tool_name": "Bash",
        "tool_input": {
          "command": "npm test -- webhook"
        },
        "tool_use_id": "tu_007"
      }
    },
    {
      "id": "evt_00041",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 41,
      "ts": "2026-09-20T14:56:23.189Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00040",
      "payload": {
        "tool_use_id": "tu_007",
        "result_ref": null,
        "duration_ms": 6400
      }
    },
    {
      "id": "evt_00042",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 42,
      "ts": "2026-09-20T14:56:24.189Z",
      "type": "turn.ended",
      "actor": "supervisor",
      "caused_by": "evt_00041",
      "payload": {
        "turn_index": 5,
        "cost_usd": 0.011,
        "tokens": {
          "input": 980,
          "output": 150
        }
      }
    },
    {
      "id": "evt_00043",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 43,
      "ts": "2026-09-20T14:56:24.589Z",
      "type": "session.ended",
      "actor": "agent",
      "caused_by": "evt_00042",
      "payload": {
        "ended_by": {
          "reason": "completed",
          "actor": "agent",
          "caused_by": "evt_00042"
        }
      }
    },
    {
      "id": "evt_00044",
      "session_id": "b4b7a1a0-2f3e-4a6b-9c1d-7e2f5a8b3c11",
      "task_id": "task-101",
      "seq": 44,
      "ts": "2026-09-20T14:56:24.789Z",
      "type": "process.exited",
      "actor": "supervisor",
      "caused_by": "evt_00043",
      "payload": {
        "exit_code": 0,
        "term_signal": null,
        "ended_by": {
          "reason": "completed",
          "actor": "agent",
          "caused_by": "evt_00043"
        }
      }
    },
    {
      "id": "evt_00045",
      "session_id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "seq": 1,
      "ts": "2026-09-20T13:38:45.189Z",
      "type": "session.started",
      "actor": "supervisor",
      "caused_by": null,
      "payload": {
        "adapter": "claude",
        "runtime": "local",
        "cwd": "/home/user/task-board-ui",
        "argv": [
          "-p",
          "--session-id",
          "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
          "--input-format",
          "stream-json",
          "--output-format",
          "stream-json"
        ],
        "capabilities": [
          "interrupt_receipt_v1"
        ]
      }
    },
    {
      "id": "evt_00046",
      "session_id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "seq": 2,
      "ts": "2026-09-20T13:38:45.489Z",
      "type": "process.spawned",
      "actor": "supervisor",
      "caused_by": "evt_00045",
      "payload": {
        "pid": 48901,
        "nonce": "n-1a44bd",
        "argv": [
          "claude",
          "-p",
          "--session-id",
          "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02"
        ],
        "cwd": "/home/user/task-board-ui"
      }
    },
    {
      "id": "evt_00047",
      "session_id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "seq": 3,
      "ts": "2026-09-20T13:38:45.689Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00046",
      "payload": {
        "turn_index": 1
      }
    },
    {
      "id": "evt_00048",
      "session_id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "seq": 4,
      "ts": "2026-09-20T13:38:45.889Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00047",
      "payload": {
        "text": "Paginate the tasks list, 25 per page.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00049",
      "session_id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "seq": 5,
      "ts": "2026-09-20T13:38:48.289Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00048",
      "payload": {
        "text": "On it — checking the current list component."
      }
    },
    {
      "id": "evt_00050",
      "session_id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "seq": 6,
      "ts": "2026-09-20T13:38:48.389Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00049",
      "payload": {
        "tool_name": "Read",
        "tool_input": {
          "file_path": "src/ui/tasks-list.js"
        },
        "tool_use_id": "tu_101"
      }
    },
    {
      "id": "evt_00051",
      "session_id": "c2d8e4f1-9a3b-4c5d-8e6f-1a2b3c4d5e02",
      "task_id": "task-102",
      "seq": 7,
      "ts": "2026-09-20T13:38:48.789Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00050",
      "payload": {
        "tool_use_id": "tu_101",
        "result_ref": null,
        "duration_ms": 90
      }
    },
    {
      "id": "evt_00052",
      "session_id": "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
      "task_id": "task-103",
      "seq": 1,
      "ts": "2026-09-20T12:38:45.189Z",
      "type": "session.started",
      "actor": "supervisor",
      "caused_by": null,
      "payload": {
        "adapter": "claude",
        "runtime": "local",
        "cwd": "/home/user/auth-service",
        "argv": [
          "-p",
          "--session-id",
          "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
          "--input-format",
          "stream-json",
          "--output-format",
          "stream-json"
        ],
        "capabilities": [
          "interrupt_receipt_v1"
        ]
      }
    },
    {
      "id": "evt_00053",
      "session_id": "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
      "task_id": "task-103",
      "seq": 2,
      "ts": "2026-09-20T12:38:45.489Z",
      "type": "process.spawned",
      "actor": "supervisor",
      "caused_by": "evt_00052",
      "payload": {
        "pid": 49022,
        "nonce": "n-8e12ac",
        "argv": [
          "claude",
          "-p",
          "--session-id",
          "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03"
        ],
        "cwd": "/home/user/auth-service"
      }
    },
    {
      "id": "evt_00054",
      "session_id": "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
      "task_id": "task-103",
      "seq": 3,
      "ts": "2026-09-20T12:38:45.689Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00053",
      "payload": {
        "turn_index": 1
      }
    },
    {
      "id": "evt_00055",
      "session_id": "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
      "task_id": "task-103",
      "seq": 4,
      "ts": "2026-09-20T12:38:45.889Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00054",
      "payload": {
        "text": "Figure out why test_auth_refresh flakes in CI.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00056",
      "session_id": "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
      "task_id": "task-103",
      "seq": 5,
      "ts": "2026-09-20T12:38:50.189Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00055",
      "payload": {
        "text": "It fails about 1 in 8 runs. I can't tell if it's a race in the token refresh or a test-only timing issue — which should I assume?"
      }
    },
    {
      "id": "evt_00057",
      "session_id": "d3e9f5a2-0b4c-4d5e-9f7a-2b3c4d5e6f03",
      "task_id": "task-103",
      "seq": 6,
      "ts": "2026-09-20T12:38:50.389Z",
      "type": "health.changed",
      "actor": "supervisor",
      "caused_by": "evt_00056",
      "payload": {
        "from": "working",
        "to": "waiting_for_input",
        "tier": 0,
        "evidence": {
          "hook": "agent_needs_input"
        }
      }
    },
    {
      "id": "evt_00058",
      "session_id": "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
      "task_id": "task-104",
      "seq": 1,
      "ts": "2026-09-20T11:38:45.189Z",
      "type": "session.started",
      "actor": "supervisor",
      "caused_by": null,
      "payload": {
        "adapter": "claude",
        "runtime": "local",
        "cwd": "/home/user/webhook-service",
        "argv": [
          "-p",
          "--session-id",
          "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
          "--input-format",
          "stream-json",
          "--output-format",
          "stream-json"
        ],
        "capabilities": [
          "interrupt_receipt_v1"
        ]
      }
    },
    {
      "id": "evt_00059",
      "session_id": "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
      "task_id": "task-104",
      "seq": 2,
      "ts": "2026-09-20T11:38:45.489Z",
      "type": "process.spawned",
      "actor": "supervisor",
      "caused_by": "evt_00058",
      "payload": {
        "pid": 49110,
        "nonce": "n-2b93de",
        "argv": [
          "claude",
          "-p",
          "--session-id",
          "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04"
        ],
        "cwd": "/home/user/webhook-service"
      }
    },
    {
      "id": "evt_00060",
      "session_id": "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
      "task_id": "task-104",
      "seq": 3,
      "ts": "2026-09-20T11:38:45.689Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00059",
      "payload": {
        "turn_index": 1
      }
    },
    {
      "id": "evt_00061",
      "session_id": "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
      "task_id": "task-104",
      "seq": 4,
      "ts": "2026-09-20T11:38:45.889Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00060",
      "payload": {
        "text": "Bump all patch-level deps and confirm nothing breaks.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00062",
      "session_id": "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
      "task_id": "task-104",
      "seq": 5,
      "ts": "2026-09-20T11:38:46.189Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00061",
      "payload": {
        "tool_name": "Bash",
        "tool_input": {
          "command": "npm outdated"
        },
        "tool_use_id": "tu_301"
      }
    },
    {
      "id": "evt_00063",
      "session_id": "e4f0a6b3-1c5d-4e6f-0a8b-3c4d5e6f7a04",
      "task_id": "task-104",
      "seq": 6,
      "ts": "2026-09-20T11:38:46.589Z",
      "type": "health.changed",
      "actor": "supervisor",
      "caused_by": "evt_00062",
      "payload": {
        "from": "working",
        "to": "rate_limited",
        "tier": 0,
        "evidence": {
          "reason": "api_retry",
          "error_status": 429,
          "attempt": 2,
          "retry_delay_ms": 8000
        }
      }
    },
    {
      "id": "evt_00064",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 1,
      "ts": "2026-09-20T10:38:45.189Z",
      "type": "session.started",
      "actor": "supervisor",
      "caused_by": null,
      "payload": {
        "adapter": "claude",
        "runtime": "local",
        "cwd": "/home/user/scheduler",
        "argv": [
          "-p",
          "--session-id",
          "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
          "--input-format",
          "stream-json",
          "--output-format",
          "stream-json"
        ],
        "capabilities": [
          "interrupt_receipt_v1"
        ]
      }
    },
    {
      "id": "evt_00065",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 2,
      "ts": "2026-09-20T10:38:45.489Z",
      "type": "process.spawned",
      "actor": "supervisor",
      "caused_by": "evt_00064",
      "payload": {
        "pid": 49207,
        "nonce": "n-9f04ab",
        "argv": [
          "claude",
          "-p",
          "--session-id",
          "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05"
        ],
        "cwd": "/home/user/scheduler"
      }
    },
    {
      "id": "evt_00066",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 3,
      "ts": "2026-09-20T10:38:45.689Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00065",
      "payload": {
        "turn_index": 1
      }
    },
    {
      "id": "evt_00067",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 4,
      "ts": "2026-09-20T10:38:45.889Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00066",
      "payload": {
        "text": "Scheduler jobs run in server-local time; convert to UTC internally.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00068",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 5,
      "ts": "2026-09-20T10:38:46.189Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00067",
      "payload": {
        "tool_name": "Bash",
        "tool_input": {
          "command": "grep -rn \"new Date(\" src/scheduler"
        },
        "tool_use_id": "tu_401"
      }
    },
    {
      "id": "evt_00069",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 6,
      "ts": "2026-09-20T10:38:46.789Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00068",
      "payload": {
        "tool_use_id": "tu_401",
        "result_ref": null,
        "duration_ms": 80
      }
    },
    {
      "id": "evt_00070",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 7,
      "ts": "2026-09-20T10:38:48.189Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00069",
      "payload": {
        "tool_name": "Bash",
        "tool_input": {
          "command": "grep -rn \"new Date(\" src/scheduler"
        },
        "tool_use_id": "tu_402"
      }
    },
    {
      "id": "evt_00071",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 8,
      "ts": "2026-09-20T10:38:48.789Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00070",
      "payload": {
        "tool_use_id": "tu_402",
        "result_ref": null,
        "duration_ms": 75
      }
    },
    {
      "id": "evt_00072",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 9,
      "ts": "2026-09-20T10:38:50.189Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00071",
      "payload": {
        "tool_name": "Bash",
        "tool_input": {
          "command": "grep -rn \"new Date(\" src/scheduler"
        },
        "tool_use_id": "tu_403"
      }
    },
    {
      "id": "evt_00073",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 10,
      "ts": "2026-09-20T10:38:50.789Z",
      "type": "tool.completed",
      "actor": "agent",
      "caused_by": "evt_00072",
      "payload": {
        "tool_use_id": "tu_403",
        "result_ref": null,
        "duration_ms": 78
      }
    },
    {
      "id": "evt_00074",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 11,
      "ts": "2026-09-20T10:38:50.989Z",
      "type": "health.changed",
      "actor": "supervisor",
      "caused_by": "evt_00073",
      "payload": {
        "from": "working",
        "to": "stuck",
        "tier": 1,
        "evidence": {
          "reason": "repeated_tool_input",
          "count": 3,
          "tool_name": "Bash",
          "tool_input": {
            "command": "grep -rn \"new Date(\" src/scheduler"
          }
        }
      }
    },
    {
      "id": "evt_00075",
      "session_id": "f5a1b7c4-2d6e-4f7a-1b9c-4d5e6f7a8b05",
      "task_id": "task-105",
      "seq": 12,
      "ts": "2026-09-20T10:38:51.189Z",
      "type": "nudge.sent",
      "actor": "watchdog",
      "caused_by": "evt_00074",
      "payload": {
        "text": "Try `grep -rln new Date src/scheduler` instead — the previous pattern isn't matching because of how the shell escapes parentheses here. Then review each file directly.",
        "tier": 2,
        "verdict": "suggest_alternative"
      }
    },
    {
      "id": "evt_00076",
      "session_id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "seq": 1,
      "ts": "2026-09-20T09:38:45.189Z",
      "type": "session.started",
      "actor": "supervisor",
      "caused_by": null,
      "payload": {
        "adapter": "claude",
        "runtime": "local",
        "cwd": "/home/user/config-loader",
        "argv": [
          "-p",
          "--session-id",
          "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
          "--input-format",
          "stream-json",
          "--output-format",
          "stream-json"
        ],
        "capabilities": [
          "interrupt_receipt_v1"
        ]
      }
    },
    {
      "id": "evt_00077",
      "session_id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "seq": 2,
      "ts": "2026-09-20T09:38:45.489Z",
      "type": "process.spawned",
      "actor": "supervisor",
      "caused_by": "evt_00076",
      "payload": {
        "pid": 51820,
        "nonce": "n-3c88f1",
        "argv": [
          "claude",
          "-p",
          "--session-id",
          "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06"
        ],
        "cwd": "/home/user/config-loader"
      }
    },
    {
      "id": "evt_00078",
      "session_id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "seq": 3,
      "ts": "2026-09-20T09:38:45.689Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00077",
      "payload": {
        "turn_index": 1
      }
    },
    {
      "id": "evt_00079",
      "session_id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "seq": 4,
      "ts": "2026-09-20T09:38:45.889Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00078",
      "payload": {
        "text": "Convert the config loader to async/await, keep the public API the same.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00080",
      "session_id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "seq": 5,
      "ts": "2026-09-20T09:38:46.189Z",
      "type": "tool.requested",
      "actor": "agent",
      "caused_by": "evt_00079",
      "payload": {
        "tool_name": "Edit",
        "tool_input": {
          "file_path": "src/config/loader.js",
          "summary": "convert to async/await"
        },
        "tool_use_id": "tu_501"
      }
    },
    {
      "id": "evt_00081",
      "session_id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "seq": 6,
      "ts": "2026-09-20T09:49:25.189Z",
      "type": "process.exited",
      "actor": "supervisor",
      "caused_by": "evt_00080",
      "payload": {
        "exit_code": null,
        "term_signal": "SIGKILL",
        "ended_by": {
          "reason": "orphan_reaped",
          "actor": "supervisor",
          "caused_by": "evt_00080"
        }
      }
    },
    {
      "id": "evt_00082",
      "session_id": "a6b2c8d5-3e7f-4a8b-2c0d-5e6f7a8b9c06",
      "task_id": "task-106",
      "seq": 7,
      "ts": "2026-09-20T09:49:25.389Z",
      "type": "session.ended",
      "actor": "supervisor",
      "caused_by": "evt_00081",
      "payload": {
        "ended_by": {
          "reason": "crashed",
          "actor": "supervisor",
          "caused_by": "evt_00081"
        }
      }
    },
    {
      "id": "evt_00083",
      "session_id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "seq": 1,
      "ts": "2026-09-20T13:08:45.189Z",
      "type": "session.started",
      "actor": "supervisor",
      "caused_by": null,
      "payload": {
        "adapter": "claude",
        "runtime": "local",
        "cwd": "/home/user/webhook-service",
        "argv": [
          "-p",
          "--session-id",
          "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
          "--input-format",
          "stream-json",
          "--output-format",
          "stream-json"
        ],
        "capabilities": [
          "interrupt_receipt_v1"
        ]
      }
    },
    {
      "id": "evt_00084",
      "session_id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "seq": 2,
      "ts": "2026-09-20T13:08:45.489Z",
      "type": "process.spawned",
      "actor": "supervisor",
      "caused_by": "evt_00083",
      "payload": {
        "pid": 49315,
        "nonce": "n-5d21ef",
        "argv": [
          "claude",
          "-p",
          "--session-id",
          "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07"
        ],
        "cwd": "/home/user/webhook-service"
      }
    },
    {
      "id": "evt_00085",
      "session_id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "seq": 3,
      "ts": "2026-09-20T13:08:45.689Z",
      "type": "turn.started",
      "actor": "supervisor",
      "caused_by": "evt_00084",
      "payload": {
        "turn_index": 1
      }
    },
    {
      "id": "evt_00086",
      "session_id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "seq": 4,
      "ts": "2026-09-20T13:08:45.889Z",
      "type": "message.user",
      "actor": "human",
      "caused_by": "evt_00085",
      "payload": {
        "text": "The HMAC check rejects valid signatures from the new partner — patch it.",
        "source": "operator"
      }
    },
    {
      "id": "evt_00087",
      "session_id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "seq": 5,
      "ts": "2026-09-20T13:08:48.189Z",
      "type": "message.assistant",
      "actor": "agent",
      "caused_by": "evt_00086",
      "payload": {
        "text": "The partner's docs and their actual payloads disagree on header casing. I'd rather not guess."
      }
    },
    {
      "id": "evt_00088",
      "session_id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "seq": 6,
      "ts": "2026-09-20T13:08:50.189Z",
      "type": "takeover.requested",
      "actor": "human",
      "caused_by": "evt_00087",
      "payload": {}
    },
    {
      "id": "evt_00089",
      "session_id": "b7c3d9e6-4f8a-4b9c-3d1e-6f7a8b9c0d07",
      "task_id": "task-107",
      "seq": 7,
      "ts": "2026-09-20T13:08:51.189Z",
      "type": "takeover.acquired",
      "actor": "human",
      "caused_by": "evt_00088",
      "payload": {}
    }
  ]
};
